# 作用：当有新的广告位申请时，自动指派给 quanac-lcx
name: Auto Assign

on:
  issues:
    types: [opened, labeled]

permissions:
  issues: write
  pull-requests: write
  repository-projects: write
  contents: read  

jobs:
  assign-issue:
    runs-on: ubuntu-latest
    steps:
      - name: Assign issue to quanac-lcx
        if: contains(github.event.issue.labels.*.name, 'advertising application')
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const issue = context.issue;
            const assignee = 'quanac-lcx';
            
            try {
              const currentAssignees = context.issue.assignees.map(a => a.login);
              
              if (currentAssignees.includes(assignee)) {
                console.log(`Issue #${issue.number} is already assigned to ${assignee}`);
                return;
              }
              
              await github.rest.issues.addAssignees({
                owner: issue.owner,
                repo: issue.repo,
                issue_number: issue.number,
                assignees: [assignee]
              });
              
              console.log(`Successfully assigned issue #${issue.number} to ${assignee}`);
            } catch (error) {
              console.error(`Failed to assign issue:`, error);
              throw error;
            }
