# 作用：当有新的广告位申请时，自动指派给 quanac-lcx
name: Auto Assign Advertising Applications

on:
  issues:
    types: [opened, labeled]

permissions:
  issues: write

jobs:
  assign-issue:
    runs-on: ubuntu-latest
    steps:
      - name: Assign issue to quanac-lcx
        if: contains(github.event.issue.labels.*.name, 'advertising application')
        uses: actions/github-script@v7 
        with:
          github-token: ${{ secrets.ASSIGNMENT_TOKEN }}
          script: |
            const { owner, repo, number: issue_number } = context.issue;
            const assignee = 'quanac-lcx';
            
            try {
              const { data: issue } = await github.rest.issues.get({
                owner,
                repo,
                issue_number
              });
              
              const currentAssignees = issue.assignees.map(a => a.login);
              
              if (currentAssignees.includes(assignee)) {
                console.log(`Issue #${issue_number} 已指派给 ${assignee}`);
                return;
              }
              
              await github.rest.issues.addAssignees({
                owner,
                repo,
                issue_number,
                assignees: [assignee]
              });
              
              console.log(`成功将 Issue #${issue_number} 指派给 ${assignee}`);
            } catch (error) {
              console.error(`ERR:`, error.response?.data || error.message);
              throw error;
            }
